### ISSUE TITLE
Latest release is looking for nonexistent version of pytz

### ISSUE THREAD

**Issue by Scotchester** [tkhyn/l18n#6]
Hi there,

It looks like l18n looks for a version of pytz matching its own version number: https://github.com/tkhyn/l18n/blob/0dd6ac867f2bc83150a7b6719a6c4ee003e36280/setup.py#L115-L118

The new release of l18n is called 2020.6, but the latest release of pytz is 2020.1, causing the installation to fail.

**Comment by tkhyn** [comment]
Fixed in new release, sorry about that, it looks like I mixed up pytz version with another one that uses the same numbering system.

**Comment by Scotchester** [comment]
Back in business; thank you!
