### ISSUE TITLE
Publish wheels

### ISSUE THREAD

**Issue by vsalvino** [tkhyn/l18n#7]
I'm wondering if there is any reason why wheels (.whl) are not being published in addition to the source distributions? One advantage to wheels from the python infrastructure standpoint is they install much faster as PyPI is able to pre-resolve the dependencies. And if your package is "pure" python (no C extensions) then building a wheel is very simple.

I am trying to optimize our dependency tree (coderedcms) and am therefore reaching out to any of our dependencies who do not yet publish in wheel format. Let me know if you are able to do this - I would be happy to help.

The command to build both source distribution and wheel is:

```
$ python setup.py sdist bdist_wheel
```

Then upload both as usual to PyPI.

For more into see: https://pythonwheels.com/

**Comment by thibaudcolas** [comment]
@tkhyn 👋  if you have a chance, it’d be nice to get your thoughts on this.

We’re using `l18n` in Wagtail to display translated timezone names, but as we audit our package’s installation times, we’re starting to wonder if it really is worthwhile to retain l18n as a dependency. Publishing this as a wheel would go a long way, and is now the standard practice for all Python projects where this is an option.

**Comment by tkhyn** [comment]
H @vsalvino and @thibaudcolas and sorry for the delay, I have just published a wheel for the latest l18n version. Could you let me know if it improves things on your ends?

**Comment by thibaudcolas** [comment]
Hi @tkhyn, I can confirm it definitely does. Thank you for making this happen!
